// include from either GLSL or C++
#ifndef ROCKY_DEFINES
#define ROCKY_DEFINES

#define VDS_DESCRIPTOR_SET_INDEX             1

#define BINDING_VDS_VSG_LIGHTS               0
#define BINDING_VDS_VSG_VIEWPORTS            1
#define BINDING_VDS_RENDER_PARAMS           10
#define BINDING_VDS_FRUSTUM_GRID_PARAMS     11
#define BINDING_VDS_FRUSTUMS                12

#define BINDING_DECAL_TILES                  6
#define BINDING_DECALS                       7
#define BINDING_MAP_SETTINGS                 8
#define BINDING_TERRAIN_SETTINGS             9

#define BINDING_TERRAIN_COLOR               11
#define BINDING_TERRAIN_ELEVATION           12
#define BINDING_TERRAIN_TILE                13


#define FRUSTUM_GRID_TILES_PER_THREAD_GROUP 16
#define MAX_DECALS_PER_TILE                 16


#ifdef __cplusplus

#define TYPE_VDS_RENDER_PARAMS        VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER
#define TYPE_VDS_FRUSTUM_GRID_PARAMS  VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER
#define TYPE_VDS_FRUSTUMS             VK_DESCRIPTOR_TYPE_STORAGE_BUFFER

#define TYPE_DECAL_TILES              VK_DESCRIPTOR_TYPE_STORAGE_BUFFER
#define TYPE_DECALS                   VK_DESCRIPTOR_TYPE_STORAGE_BUFFER

#define TYPE_MAP_SETTINGS             VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER
#define TYPE_TERRAIN_SETTINGS         VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER
#define TYPE_TERRAIN_TILE_SETTINGS    VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER

#endif

#endif // ROCKY_DEFINES

