#version 450
/**
 * rocky c++
 * Copyright 2026 Pelican Mapping
 * MIT License
 */
#define SSBOS_ARE_WRITABLE

// inspired by https://github.com/zimengyang/ForwardPlus_Vulkan
#pragma include "rocky.frustumgrid.h.glsl"

layout(local_size_x = FRUSTUM_GRID_TILES_PER_THREAD_GROUP, 
       local_size_y = FRUSTUM_GRID_TILES_PER_THREAD_GROUP) in;


vec4 screenToView(in vec4 screen)
{
    // screen to clip (viewport-relative):
    vec2 uv = (screen.xy - vec2(u_viewport.xy)) / vec2(u_viewport.zw);
    vec4 clip = vec4(uv * 2.0 - 1.0, screen.z, screen.w);

    // clip to view:
    vec4 view = u_invProjMatrix * clip;
    view /= view.w;
    return view;
}

vec4 createPlane(in vec3 p0, in vec3 p1, in vec3 p2)
{
    vec4 plane;
    vec3 v0 = p1 - p0;
    vec3 v1 = p2 - p0;
    plane.xyz = normalize(cross(v0, v1));
    plane.w = dot(plane.xyz, p0);
    return plane;
}

// We need to run this whenever the screen size changes.
// If we decide we need Z, it will need to run any time the near/far changes.
void main()
{
    if (gl_GlobalInvocationID.x >= u_numTiles.x || gl_GlobalInvocationID.y >= u_numTiles.y)
        return;

    uint tile = gl_GlobalInvocationID.y * u_numTiles.x + gl_GlobalInvocationID.x;

    // screen space corners of tile.
    const float z = 0.0;
    vec2 tileMin = vec2(gl_GlobalInvocationID.xy) * float(u_pixelsPerTile);
    vec2 tileMax = min(tileMin + vec2(float(u_pixelsPerTile)), vec2(u_viewport.zw));
    vec2 viewportOrigin = vec2(u_viewport.xy);

    vec4 UL = vec4(viewportOrigin + vec2(tileMin.x, tileMin.y), z, 1.0);
    vec4 UR = vec4(viewportOrigin + vec2(tileMax.x, tileMin.y), z, 1.0);
    vec4 LL = vec4(viewportOrigin + vec2(tileMin.x, tileMax.y), z, 1.0);
    vec4 LR = vec4(viewportOrigin + vec2(tileMax.x, tileMax.y), z, 1.0);

    // convert to view space:
    vec3 UL_VS = screenToView(UL).xyz;
    vec3 UR_VS = screenToView(UR).xyz;
    vec3 LL_VS = screenToView(LL).xyz;
    vec3 LR_VS = screenToView(LR).xyz;

    // and make the bounding planes:
    if (u_projIsOrtho == 1)
    {
        // orthographic projection matrix:
        float minX = min(min(UL_VS.x, UR_VS.x), min(LL_VS.x, LR_VS.x));
        float maxX = max(max(UL_VS.x, UR_VS.x), max(LL_VS.x, LR_VS.x));
        float minY = min(min(UL_VS.y, UR_VS.y), min(LL_VS.y, LR_VS.y));
        float maxY = max(max(UL_VS.y, UR_VS.y), max(LL_VS.y, LR_VS.y));

        b_frustums.frustum[tile].planes[0] = vec4(1.0, 0.0, 0.0, minX);    // left
        b_frustums.frustum[tile].planes[1] = vec4(-1.0, 0.0, 0.0, -maxX);  // right
        b_frustums.frustum[tile].planes[2] = vec4(0.0, -1.0, 0.0, -maxY);  // top
        b_frustums.frustum[tile].planes[3] = vec4(0.0, 1.0, 0.0, minY);    // bottom 
    }
    else
    {
        // perspective projection matrix:
        const vec3 eye = vec3(0);
        b_frustums.frustum[tile].planes[0] = createPlane(eye, LL_VS, UL_VS); // left plane
        b_frustums.frustum[tile].planes[1] = createPlane(eye, UR_VS, LR_VS); // right plane
        b_frustums.frustum[tile].planes[2] = createPlane(eye, UL_VS, UR_VS); // top plane
        b_frustums.frustum[tile].planes[3] = createPlane(eye, LR_VS, LL_VS); // bottom plane
    }
}
