/**
 * rocky c++
 * Copyright 2026 Pelican Mapping
 * MIT License
 */
#pragma once
#include <rocky/ecs/Overlay.h>
#include <rocky/ecs/ProjectedTexture.h>
#include <rocky/SRS.h>
#include <rocky/vsg/ecs/ECSNode.h>
#include <rocky/vsg/ecs/TextureResource.h>
#include <array>

namespace ROCKY_NAMESPACE::detail
{
    /**
     * Marker on a Transform generated by OverlayBakeSystem's source fit.
     * It distinguishes system-owned projector placement from a Transform the
     * application supplied, so refits and teardown never overwrite or remove
     * caller-owned state.
     */
    struct AutoOverlayTransform
    {
    };

    //! Compatibility name for the output of an Overlay bake. New code should
    //! consume TextureResource instead.
    using OverlayBakeTexture = TextureResource;

    //! Internal progression of one offscreen bake's resource generation.
    enum class OverlayBakePhase
    {
        WaitingForSources, //!< No complete/active source set yet.
        Priming,           //!< Resources exist; allow source systems to prepare.
        Baking,            //!< Offscreen commands are producing a new generation.
        Ready              //!< The published TextureResource matches the job.
    };

    /**
     * Renderer-private state for one normalized RenderTexture job.
     *
     * VSG objects belong to the job and are disposed when this component is
     * removed. Revisions divide invalidation into projector bounds and
     * rendered content. generationPending advances the externally visible
     * RenderTextureStatus only after a completed bake is published.
     */
    struct OverlayBakeDetail : public Component<OverlayBakeDetail>
    {
        // Offscreen resource graph owned by this bake job.
        vsg::ref_ptr<vsg::ImageInfo> texture;
        vsg::ref_ptr<vsg::RenderGraph> renderGraph;
        vsg::ref_ptr<vsg::Node> viewNode;
        vsg::ref_ptr<vsg::CommandGraph> hostCommandGraph;

        // Allocation configuration. A size/depth change recreates the job.
        glm::uvec2 textureSize = { 0u, 0u };
        bool useDepthBuffer = false;

        // Last source generations consumed by fitting and rendering.
        std::size_t boundsRevision = 0u;
        std::size_t contentRevision = 0u;
        bool boundsRevisionValid = false;
        bool contentRevisionValid = false;

        // Publication and phase-machine state.
        bool autoTransformDirty = true;
        bool fitToSources = true;
        bool published = false;
        bool generationPending = true;
        OverlayBakePhase phase = OverlayBakePhase::WaitingForSources;
    };
}

namespace ROCKY_NAMESPACE
{
    /**
     * Produces RTT payloads and shared auto-fit projectors for Overlay.
     *
     * Raster mode:
     *   sources -> offscreen RenderGraph -> TextureResource
     * Vector mode:
     *   sources -> fitted AutoOverlayTransform (SlugSystem builds the atlas)
     *
     * Keeping source fitting here makes both modes use the same bounds,
     * padding, antimeridian handling, and ownership rules.
     */
    class ROCKY_EXPORT OverlayBakeSystemNode : public vsg::Inherit<detail::SimpleSystemNodeBase, OverlayBakeSystemNode>
    {
    public:
        OverlayBakeSystemNode(Registry& registry);

        //! System collection from which render-to-texture capabilities are discovered.
        //! This is rescanned during update so extensions can register live.
        ECSNode* renderSourceSystems = nullptr;
        vsg::ref_ptr<vsg::Group> bakeScene;
        SRS worldSRS;
        unsigned textureSize = 512u;

        //! Maximum number of new offscreen render targets to create and
        //! synchronously compile in one frame. Zero means unlimited.
        unsigned maxResourceSetupsPerFrame = 2u;

        // Advanced tuning factor for fallback auto-computed overlay depth thickness.
        // Resident terrain bounds override the receiving depth when available.
        // 1.0 = default behavior; >1.0 = safer/thicker; <1.0 = tighter/faster.
        float depthSafetyFactor = 1.0f;

    public: // SimpleSystemNodeBase
        void initialize(VSGContext) override;
        void update(VSGContext) override;

    private:
        // Color-only and depth-enabled bakes need separate view IDs so VSG can
        // compile compatible graphics-pipeline implementations for each render pass.
        std::array<vsg::ref_ptr<vsg::Camera>, 2> _sharedCameras;
        std::array<vsg::ref_ptr<vsg::View>, 2> _sharedViews;
        std::array<vsg::ref_ptr<vsg::RenderPass>, 2> _sharedRenderPasses;
        vsg::ref_ptr<vsg::Context> _resourceContext;
        std::vector<RenderTextureParticipant*> _renderParticipants;
        mutable float _lastDepthSafetyFactor = -1.0f;
        SRS _lastWorldSRS;
        void refreshRenderParticipants();

        void on_construct_Overlay(entt::registry& r, entt::entity e);
        void on_destroy_Overlay(entt::registry& r, entt::entity e);
        void on_update_Overlay(entt::registry& r, entt::entity e);
        void on_construct_RenderTexture(entt::registry& r, entt::entity e);
        void on_destroy_RenderTexture(entt::registry& r, entt::entity e);
        void on_update_RenderTexture(entt::registry& r, entt::entity e);
        void on_destroy_OverlayBakeDetail(entt::registry& r, entt::entity e);

        bool createBakeResources(
            VSGContext vsgcontext,
            const glm::uvec2& textureSize,
            bool useDepthBuffer,
            vsg::ref_ptr<vsg::ImageInfo>& outTexture,
            vsg::ref_ptr<vsg::RenderGraph>& outRenderGraph,
            vsg::ref_ptr<vsg::Node>& outViewNode,
            vsg::ref_ptr<vsg::CommandGraph>& outHostCommandGraph);
        bool updateBakeCamera(
            entt::registry& r, entt::entity e_overlay,
            detail::OverlayBakeDetail& detail, bool recomputeAutoTransform) const;
    };
}

EVSG_type_name(rocky::OverlayBakeSystemNode)
