# Platform specific settings

set(ROCKY_INSTALL_RUNTIME_FOLDER "bin${ROCKY_INSTALL_FOLDER_SUFFIX}")  # executables
set(ROCKY_INSTALL_LIBRARY_FOLDER "bin${ROCKY_INSTALL_FOLDER_SUFFIX}")  # .dll/.so
set(ROCKY_INSTALL_ARCHIVE_FOLDER "lib${ROCKY_INSTALL_FOLDER_SUFFIX}")  # .lib/.a

if(UNIX)
    set(ROCKY_INSTALL_LIBRARY_FOLDER ${ROCKY_INSTALL_ARCHIVE_FOLDER})
endif()
